#!/bin/bash -l
#
#SBATCH --job-name="Scalasca profile"
#SBATCH --nodes=4
#SBATCH --ntasks-per-node=2
#SBATCH --cpus-per-task=4
#SBATCH --time=30:00
#SBATCH --mem-per-cpu=2000

# Loading Scalasca will also load OpenMPI
module load Scalasca

export OMP_PROC_BIND=true
export OMP_NUM_THREADS=${SLURM_CPUS_PER_TASK}

export SRUN_CPUS_PER_TASK=${SLURM_CPUS_PER_TASK}

scalasca -analyze srun ./myapp_instr example_inputs/simple/param_simple.txt

